

# Repos not syncing after upgrade in support-glovo <!-- Ticket Title  Hint: include keywords to make it searchable -->



- Zendesk Link: [#4372](https://sourcegraph.zendesk.com/agent/tickets/4372)

- Application engineer: Mariam Adedeji

- Customer: Glovo <!-- Redact if this contains personally identifying information -->

- Date: Oct 30


<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->

<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->



## Technical Environment

- Version: 3.33.1​

- Deployment: docker-compose

- External Services: GITHUB

- Auth Providers: github





## Links
<!-- Data for application engineer manual entry -->
- Slack Links:https://sourcegraph.slack.com/archives/C01NDS6BVBQ/p1635604382052800

- GitHub Issue Link: N/A

- Doc Update Link: N/A



## Summary

### Description of Customer Issue

After upgrading 3.30.1 to 3.31.2, I always see a message like X repositories could not be synced, we still have 18 repos that aren't getting synced. It’s not looking great though :grimacing: went up to 33 repos now



### Troubleshooting Steps

Requested for gitserver logs

Reviewed the logs shared



### Resolution

Could you try to check your ulimit value first by running this command
ulimit -n
Then you can increase it with this command
ulimit -n 10000You can make this setting permanent for every shell session by adding the following line to your .*rc file (usually .bashrc or .zshrc):

# increase max number of file descriptors for running a sourcegraph instance.
ulimit -n 10000



### Relevant Docs Pages Used/Created



### Relevant Error / Logs

<!-- Please redact keys, tokens, and personal identifying information -->

lvl=eror msg="Failed to fetch" repo=github.com/glovo/terraform-datadog error="failed to update with output \"\": pipe2: too many open files"
lvl=eror msg="performing background repo update" error="failed to fetch: failed to update with output \"\": pipe2: too many open files"

