
# Databricks: Receiving a Sync error for repo that shouldn't be syncing at all <!-- Ticket Title  Hint: include keywords to make it searchable -->

- Zendesk Link: [#8081](https://sourcegraph.zendesk.com/agent/tickets/8081)
- Application engineer: Jason Harris
- Customer: Databricks <!-- Redact if this contains personally identifying information -->
- Date: May 9

<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->
<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->

## Technical Environment
- Version: ​3.39
- Deployment: docker-compose
- External Services:
- Auth Providers:


## Links
<!-- Data for application engineer manual entry -->
- Slack Links: https://sourcegraph.slack.com/archives/C02UM8A9M2R/p1651886151567429 
- GitHub Issue Link: https://github.com/sourcegraph/customer/issues/928 
- Doc Update Link: n/a

## Summary
### Description of Customer Issue
The customer saw a repo failing to sync in error logs for a repo the user never added.


### Troubleshooting Steps
Queried the graphql API and pgsql database for the repo, returning nothing for both queries.
Filed issue

### Resolution
What's happening here is that users are browsing to a URL like http://customer-instance/github.com/Homebrew/homebrew-core

repo-management introduced a change a while back that is mistakenly trying to sync these repos on the host but it fails to do so since this feature is intended for cloud only. It's not an issue since the repos aren't actually being cloned.

repo-management will work on a fix so that we don't try to clone them anymore which will also stop those errors logs from appearing.

### Relevant Docs Pages Used/Created

### Relevant Error / Logs
<!-- Please redact keys, tokens, and personal identifying information -->


<!-- Once complete, upload a copy to https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets as a .md file -->
<!-- Name the file 8081.md -->
