
# error setting up https with Custom Certificates in Docker Compose <!-- Ticket Title  Hint: include keywords to make it searchable -->

- Zendesk Link: [#9878](https://sourcegraph.zendesk.com/agent/tickets/9878)
- Application engineer: Riana Shahid
- Customer: on discord -- didn't want to publicly say who they're with <!-- Redact if this contains personally identifying information -->
- Date: July 20, 2022

<!-- Data populated from integration, speak to Ben Gordon or Michael Bali if not working -->
<!-- During Internal team trial, fill missing data manually (we are waiting for all data to sync) -->

## Technical Environment
- Version: ​
- Deployment: docker-compose
- External Services:
- Auth Providers:


## Links
<!-- Data for application engineer manual entry -->
- Slack Links: https://sourcegraph.slack.com/archives/C03PZABGN76/p1658327560568829
- GitHub Issue Link: 
- Doc Update Link: https://github.com/sourcegraph/sourcegraph/pull/39385

## Summary
### Customer Question
Customer initially deployed on docker but got the following errors
`"failed to connect to host=127.0.0.1 user=postgres database=sourcegraph: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}}`
```
14:00:48                  frontend | t=2022-07-20T14:00:48+0000 lvl=eror msg="API HTTP handler error response" method=POST request_uri=/.internal/configuration status_code=500 error="ConfStore.SiteGetLatest: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" trace= traceID=
14:00:48                  frontend | {"SeverityText":"ERROR","Timestamp":1658325648174335761,"InstrumentationScope":"internal.http","Caller":"trace/httptrace.go:275","Function":"github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1","Body":"slow http request, unexpected status code","Resource":{"service.name":"frontend","service.version":"3.41.1","service.instance.id":"86e1ad5c8f03"},"Attributes":{"route_name":"internal.configuration","method":"POST","url":"/.internal/configuration","code":500,"duration":92.753993671,"error":"ConfStore.SiteGetLatest: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}}
14:00:48                  frontend | t=2022-07-20T14:00:48+0000 lvl=eror msg="API HTTP handler error response" method=POST request_uri=/.internal/configuration status_code=500 error="ConfStore.SiteGetLatest: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" trace= traceID=
14:00:48                  frontend | {"SeverityText":"ERROR","Timestamp":1658325648194081828,"InstrumentationScope":"internal.http","Caller":"trace/httptrace.go:275","Function":"github.com/sourcegraph/sourcegraph/internal/trace.HTTPMiddleware.func1","Body":"slow http request, unexpected status code","Resource":{"service.name":"frontend","service.version":"3.41.1","service.instance.id":"86e1ad5c8f03"},"Attributes":{"route_name":"internal.configuration","method":"POST","url":"/.internal/configuration","code":500,"duration":92.909683291,"error":"ConfStore.SiteGetLatest: failed to connect to `host=127.0.0.1 user=postgres database=sourcegraph`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"}}
```
```
13:59:59           zoekt-webserver | 2022/07/20 13:59:58 watchdog: failed, will try 1 more times: Get "http://127.0.0.1:3070/healthz": context deadline exceeded
14:00:25           zoekt-webserver | 2022/07/20 14:00:23 DBUG: search traceID= q=TRUE Options{EstimateDocCount=false Whole=false ShardMaxMatchCount=1 TotalMaxMatchCount=1 ShardMaxImportantMatch=0 TotalMaxImportantMatch=0 MaxWallTime=0s MaxDocDisplayCount=1} Stats{ContentBytesLoaded=0 IndexBytesLoaded=0 Crashes=0 Duration=25.690126133s FileCount=0 ShardFilesConsidered=0 FilesConsidered=0 FilesLoaded=0 FilesSkipped=0 ShardsScanned=0 ShardsSkipped=1635 ShardsSkippedFilter=0 MatchCount=0 NgramMatches=0 Wait=1.400651591s}
14:00:46         zoekt-indexserver | Terminating zoekt-indexserver
14:00:47         postgres_exporter | Terminating postgres_exporter
14:00:46            syntect_server | Terminating syntect_server
14:00:47               redis-store | Terminating redis-store
```
Redeployed on docker compose 
```
caddy                            | {"level":"info","ts":1658504588.0946684,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy                            | run: adapting config using caddyfile: subject does not qualify for certificate: '{sourcegraph.corp.$DOMAIN.com}'
```

### Application Engineer Answer
regarding the errors in docker
In general, the status_code=500 errors tend to be more of a generic response. The “Repository authz config…” message can result from postgres hitting a max memory limit. Similarly, the “context deadline exceeded” errors are also related to hitting a rate limit. zoekt-webserver is responsible for running certain searches and is impacted by the number and size of the repositories you’re searching across, so depending on the queries you ran before the crash, that could have contributed to these alerts. 
<br /><br />
error in docker-compose caused by editing the caddyfile (specifically the value for `{$SRC_SITE_ADDRESS}`) which should remain untouched. docs were kind of unclear about what to do so I updated them to clarify
### Relevant Docs Pages Used/Created
https://docs.sourcegraph.com/admin/http_https_configuration#sourcegraph-via-docker-compose-caddy-2 - added the "Important" section
<!-- Once complete, upload a copy to https://github.com/sourcegraph/support-tools-internal/tree/main/resolved-tickets as a .md file -->
<!-- Name the file 9878.md -->
